### ISSUE TITLE
Items not correctly tagged

### ISSUE THREAD

**Issue by SilentChaos512** [CodersDownUnder/GemsPlusPlus#13]
**Describe the bug**
Items are not tagged correctly. Gems should be under `forge:gems/`, not your own namespace. For example, ruby should be `forge:gems/ruby` instead of `gemsplusplus:ruby`.

Correctly tagging your items will allow them to work with other mods and data packs.

**Examples from one of my mods if you need them**: https://github.com/SilentChaos512/SilentGems/tree/1.14/src/main/resources/data/forge/tags

**Versions**
Minecraft: 1.14.4
GemsPlusPlus: 1.3.4

**Comment by Trhod17** [comment]
Fixed as of 1.4.0

**Comment by WenXin20** [comment]
Hello, I'm using `v1.4.0` for `Minecraft v1.14.4` and have noticed that gem tags are not functioning at all. I believe this is because the tags are located at `data/forge/tags/gems` but should instead be located at `data/forge/tags/items/gems`. 
The gems folder should be moved into the items folder.

**Comment by Trhod17** [comment]
should be fixed in latest v1.5.0
